# Generated by Django 5.2.1 on 2025-06-21 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0002_student'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age', models.IntegerField(null=True)),
                ('Contact', models.CharField(max_length=255, null=True)),
                ('Address', models.TextField(null=True)),
                ('District', models.CharField(max_length=255, null=True)),
                ('State', models.CharField(max_length=255, null=True)),
                ('Pin', models.IntegerField(null=True)),
                ('Gender', models.CharField(max_length=255, null=True)),
                ('Experience', models.IntegerField(null=True)),
                ('Image', models.ImageField(null=True, upload_to='images/')),
                ('Course_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collegeapp.course')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
